import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import TopBar from "@/components/TopBar";
import SyncManager from "@/components/SyncManager";
import { QueryClientProvider } from "@tanstack/react-query";
import {ReactQueryDevtools} from "@tanstack/react-query-devtools";
import {queryClient} from "@/lib/queryClient";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <QueryClientProvider client={queryClient}>
        <html
            lang="en"
            className={cn("h-full antialiased", "font-sans", inter.variable)}
        >
        <body className="min-h-full flex flex-col bg-[#F9F7F3]">
        <SyncManager />
        <TopBar />
        {children}
        </body>
        </html>
        <ReactQueryDevtools initialIsOpen={false} />
      </QueryClientProvider>
  );
}
