import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import TopBar from "@/components/TopBar";
import SyncManager from "@/components/SyncManager";
import Providers from "@/components/Providers";
import { Analytics } from "@vercel/analytics/next"

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full antialiased", "font-sans", inter.variable)}
    >
      <body className="min-h-full flex flex-col bg-[#F9F7F3]">
      <Analytics />
        <Providers>
          <SyncManager />
          <TopBar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
